# Generated by Django 5.2.2 on 2025-06-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_detection_delete_plantdiagnosisresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
