# Generated by Django 5.2.2 on 2025-06-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_detection_confidence_score_detection_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
