# Generated by Django 5.2.3 on 2025-06-20 14:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_detection_flag_reason_detection_flagged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detection',
            options={'ordering': ['-created_at'], 'verbose_name': 'Plant Detection', 'verbose_name_plural': 'Plant Detections'},
        ),
        migrations.AlterField(
            model_name='detection',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
